# -*- coding: utf-8 -*-
"""covidpred_model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/162lzpyIWJNeP7LwmT59lm70iQv5MhakU

### COVID Model Development
"""

import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

data = pd.read_csv("https://github.com/animesh/covidpred/raw/master/data/corona_tested_individuals_ver_006.english.csv.zip")

X = data.drop(['corona_result'], axis=1)
y = data['corona_result']

X = X.drop(['test_date'], axis=1)

X = X.drop(['gender'], axis=1)

X = X.drop(['age_60_and_above'],axis=1)

X = X.drop(['test_indication'],axis=1)

cols = X.columns
X[cols] = X[cols].apply(pd.to_numeric, errors='coerce')

X.fillna(0,inplace=True)

X_train, X_test, y_train, y_test = train_test_split(X,y , test_size = 0.2)
model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(accuracy_score(y_test, y_pred))

print(model.predict(np.array([[0,0,0,0,0]])))

import pickle
pickle.dump(model, open("covidpred_model_v1.pkl", "wb"))

print("deseralize")
model_pk = pickle.load(open("covidpred_model_v1.pkl", "rb"))
print("Rerun predictions")
print(model.predict(np.array([[1,1,1,1,1]])))
#0.9444683521606598
#['negative']
#deseralize
#Rerun predictions
#['positive']
